// <auto-generated />
using FleetCommandAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetCommandAPI.Migrations
{
    [DbContext(typeof(FleetStarShipsContext))]
    [Migration("20231206185416_planetsMigration")]
    partial class planetsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FleetCommandAPI.Model.MissionsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Planetid")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Planetid");

                    b.ToTable("missions");
                });

            modelBuilder.Entity("FleetCommandAPI.Model.PlanetModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Population")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Terrain")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("planetModel");
                });

            modelBuilder.Entity("FleetCommandAPI.Model.StarShipModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("ships");
                });

            modelBuilder.Entity("MissionsModelStarShipModel", b =>
                {
                    b.Property<int>("missionsModelsId")
                        .HasColumnType("int");

                    b.Property<int>("starshipsid")
                        .HasColumnType("int");

                    b.HasKey("missionsModelsId", "starshipsid");

                    b.HasIndex("starshipsid");

                    b.ToTable("MissionsModelStarShipModel");
                });

            modelBuilder.Entity("FleetCommandAPI.Model.MissionsModel", b =>
                {
                    b.HasOne("FleetCommandAPI.Model.PlanetModel", "Planet")
                        .WithMany("missions")
                        .HasForeignKey("Planetid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("MissionsModelStarShipModel", b =>
                {
                    b.HasOne("FleetCommandAPI.Model.MissionsModel", null)
                        .WithMany()
                        .HasForeignKey("missionsModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetCommandAPI.Model.StarShipModel", null)
                        .WithMany()
                        .HasForeignKey("starshipsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetCommandAPI.Model.PlanetModel", b =>
                {
                    b.Navigation("missions");
                });
#pragma warning restore 612, 618
        }
    }
}
