// <auto-generated />
using FleetCommandAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetCommandAPI.Migrations
{
    [DbContext(typeof(FleetStarShipsContext))]
    partial class FleetStarShipsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FleetCommandAPI.Model.MissionsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Planet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("missions");
                });

            modelBuilder.Entity("FleetCommandAPI.Model.StarShipModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("ships");
                });

            modelBuilder.Entity("MissionsModelStarShipModel", b =>
                {
                    b.Property<int>("missionsModelsId")
                        .HasColumnType("int");

                    b.Property<int>("starshipsid")
                        .HasColumnType("int");

                    b.HasKey("missionsModelsId", "starshipsid");

                    b.HasIndex("starshipsid");

                    b.ToTable("MissionsModelStarShipModel");
                });

            modelBuilder.Entity("MissionsModelStarShipModel", b =>
                {
                    b.HasOne("FleetCommandAPI.Model.MissionsModel", null)
                        .WithMany()
                        .HasForeignKey("missionsModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetCommandAPI.Model.StarShipModel", null)
                        .WithMany()
                        .HasForeignKey("starshipsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
